# Generated by Django 5.0.6 on 2024-06-17 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seg_Mod_Graduacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecategoria', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InveCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invtitulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('slug', models.SlugField(unique=True)),
                ('invfecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('invdescripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('invdocumentacion', models.FileField(null=True, upload_to='documento/proyecto', verbose_name='Documentacion')),
                ('invdestacado', models.BooleanField(default=True)),
                ('investado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('invcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.categoria', verbose_name='Categoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioInvCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invcomentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('invFecha_post', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invproyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.invecientifica')),
            ],
            options={
                'ordering': ['-invFecha_post'],
            },
        ),
    ]
