# Generated by Django 5.0.6 on 2024-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seg_Mod_Graduacion', '0003_alter_invecientifica_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitarInv', models.BooleanField(default=True, verbose_name='Habilitar Formulario')),
            ],
        ),
    ]
