# Generated by Django 5.0.6 on 2024-06-19 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seg_Mod_Graduacion', '0004_invsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarioperfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percomentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('perFecha_post', models.DateTimeField(auto_now_add=True)),
                ('perproyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.invecientifica')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-perFecha_post'],
            },
        ),
        migrations.CreateModel(
            name='PerfildeProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertitulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('slug', models.SlugField(unique=True)),
                ('perfecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perdescripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('perdocumentacion', models.FileField(null=True, upload_to='documento/proyecto', verbose_name='Documentacion')),
                ('perestado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('percategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.categoria', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
        ),
    ]
