# Generated by Django 5.0.6 on 2024-06-19 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seg_Mod_Graduacion', '0006_alter_comentarioperfil_perproyecto_relacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioperfil',
            name='perproyecto_relacionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Seg_Mod_Graduacion.perfildeproyecto'),
        ),
    ]
