# Generated by Django 5.0.6 on 2024-06-12 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seg_Mod_Graduacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.IntegerField()),
                ('periodo_ingreso', models.CharField(max_length=50)),
                ('anio_egreso', models.IntegerField()),
                ('periodo_egreso', models.CharField(max_length=50)),
                ('nota', models.FloatField()),
                ('proyecto_final', models.OneToOneField(limit_choices_to={'estado': 'Aprobado'}, on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.proyectofinal')),
                ('usuario', models.OneToOneField(limit_choices_to={'estado': True, 'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('modalidad', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero_acta', models.CharField(max_length=50)),
                ('pdf_proyecto_final', models.FileField(upload_to='documentos/proyecto_final/')),
                ('tribunales', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Docentes'}, related_name='tribunales_documento', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(limit_choices_to={'groups__name': 'Docentes'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_documento', to=settings.AUTH_USER_MODEL)),
                ('tutor_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seg_Mod_Graduacion.tutorexterno')),
                ('titulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repositorio_Titulados.titulado')),
            ],
        ),
    ]
